version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy/index.html:/var/www/html/index.html
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
  git-server:
    container_name: git_server
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
  flask-app:
    build:
      context: ./flask-app
    container_name: flask_app
    ports:
      - "5000:5000"
